# 1. 운영체제 및 프로그램 설치(하나하나 입력하는 방식)
# FROM ubuntu:22.04

# RUN sudo apt install nodejs
# RUN sudo npm install -g yarn

# 1. 운영체제 및 프로그램 설치(이미 리눅스, node, npm, yarn 까지 모두 깔려있는 컴퓨터 다운로드 하는 방식)
FROM node:14

# 2. 내 컴퓨터에 있는 폴더나 파일을 도커 컴퓨터 안으로 복사하기
# RUN mkdir myfolder //myfolder 생성
COPY ./index.js /index.js

# 3. 도커안에서 index.js 실행시키
#RUN node index.js
CMD node index.js
#CMD와 RUN의 차이는 RUN은 위의 단계를 걸쳐서 이미지로 저장, 실행이 한꺼번에 진행되고
#CMD는 바로 윗단계까지 저장완료 된 것을 실행시킬 때 사용, 보통은 실행되어있지 않은 이미지를 실행시킬때 사용한다.
#CMD는 도커파일 안에서 한번만 사용할 수 있다.(한번만 실행시킬 수 있다.)

# 위와같이 작성하여 기능할 수 있도록 하는 것을 'docker build'라 한다.
# 이렇게 되면 하나의 파일이 만들어 지는데 이를 'docker image'라 한다.